import Head from 'next/head'
// import Image from 'next/image'
import Header from '../components/Header'
import Nav from '../components/Nav'
import Results from '../components/Results'
import styles from '../styles/Home.module.css'
import requests from '../utils/requests'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>HULU 2.O</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header/>
      <Nav/>
      <Results/>

    </div>
  )
}
export async function getServerSideProps(context){
  const query= context.query.genre
  const request= await fetch(`https://api.themoviedb.org/3/movie/550?api_key=${requests[genre]?.url || }`)

}
